name: Jamie
favicon: null
layout_spectrum: 0.71119
typography_spectrum: 0.34224
title: Jamie's First Grid Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#204f69'
    - '#4e7a90'
    - '#799da4'
    - '#fee49e'
    - '#a9893b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4234526106156409
purpose: []
